# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: app/repositories/product_repository.py
from sqlalchemy.orm import Session

from app.models.product import Product
from schemas.product_schema import ProductCreate, ProductUpdate


class ProductRepository:

    def create_product(
        self,
        db: Session,
        product: ProductCreate,
    ):
        new_product = Product(
            product_name=product.product_name,
            description=product.description,
            category_id=product.category_id,
            price=product.price,
            available_quantity=product.available_quantity,
            product_url=product.product_url,
        )

        db.add(new_product)
        db.commit()
        db.refresh(new_product)

        return new_product

    def get_all_products(
        self,
        db: Session,
    ):
        return db.query(Product).all()

    def get_product_by_id(
        self,
        db: Session,
        product_id: int,
    ):
        return db.query(Product).filter(
            Product.product_id == product_id
        ).first()

    def get_product_by_name(
        self,
        db: Session,
        product_name: str,
    ):
        return db.query(Product).filter(
            Product.product_name == product_name
        ).first()

    def search_products(
        self,
        db: Session,
        name: str | None = None,
        category_id: int | None = None,
    ):
        query = db.query(Product)

        if name:
            query = query.filter(
                Product.product_name.ilike(f"%{name}%")
            )

        if category_id:
            query = query.filter(
                Product.category_id == category_id
            )

        return query.all()

    def update_product(
        self,
        db: Session,
        product: Product,
        product_data: ProductUpdate,
    ):
        update_data = product_data.model_dump(
            exclude_unset=True
        )

        for field, value in update_data.items():
            setattr(product, field, value)

        db.commit()
        db.refresh(product)

        return product

    def delete_product(
        self,
        db: Session,
        product: Product,
    ):
        db.delete(product)
        db.commit()

        return True
