# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: services/cart_service.py

from decimal import Decimal

from fastapi import HTTPException, status
from sqlalchemy.orm import Session

from app.models.user import User
from repositories.cart_repository import CartRepository
from repositories.product_repository import ProductRepository
from schemas.cart_schema import (
    CartItemCreate,
    CartItemUpdate,
    CartSummaryResponse,
)


class CartService:

    def __init__(self):

        self.cart_repository = CartRepository()
        self.product_repository = ProductRepository()

    def _get_user_by_id(
        self,
        db: Session,
        user_id: int,
    ):

        user = db.query(User).filter(
            User.user_id == user_id
        ).first()

        if user is None:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="User not found",
            )

        return user

    def add_cart_item(
        self,
        db: Session,
        cart_item: CartItemCreate,
    ):

        self._get_user_by_id(db, cart_item.user_id)

        product = self.product_repository.get_product_by_id(
            db,
            cart_item.product_id,
        )

        if product is None:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Product not found",
            )

        if cart_item.quantity > product.available_quantity:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Requested quantity exceeds available stock",
            )

        existing_cart_item = (
            self.cart_repository.get_cart_item_by_user_and_product(
                db,
                cart_item.user_id,
                cart_item.product_id,
            )
        )

        if existing_cart_item:

            new_quantity = (
                existing_cart_item.quantity + cart_item.quantity
            )

            if new_quantity > product.available_quantity:
                raise HTTPException(
                    status_code=status.HTTP_400_BAD_REQUEST,
                    detail="Total cart quantity exceeds available stock",
                )

            return self.cart_repository.update_cart_item(
                db,
                existing_cart_item,
                new_quantity,
            )

        return self.cart_repository.create_cart_item(
            db,
            cart_item,
        )

    def get_cart(
        self,
        db: Session,
        user_id: int,
    ):

        self._get_user_by_id(db, user_id)

        return self.cart_repository.get_cart_items_by_user(
            db,
            user_id,
        )

    def update_cart_item(
        self,
        db: Session,
        cart_item_id: int,
        cart_item_data: CartItemUpdate,
    ):

        cart_item = self.cart_repository.get_cart_item_by_id(
            db,
            cart_item_id,
        )

        if cart_item is None:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Cart item not found",
            )

        product = self.product_repository.get_product_by_id(
            db,
            cart_item.product_id,
        )

        if product is None:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Product not found",
            )

        if cart_item_data.quantity > product.available_quantity:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Requested quantity exceeds available stock",
            )

        return self.cart_repository.update_cart_item(
            db,
            cart_item,
            cart_item_data.quantity,
        )

    def remove_cart_item(
        self,
        db: Session,
        cart_item_id: int,
    ):

        cart_item = self.cart_repository.get_cart_item_by_id(
            db,
            cart_item_id,
        )

        if cart_item is None:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Cart item not found",
            )

        self.cart_repository.delete_cart_item(
            db,
            cart_item,
        )

        return {
            "message": "Cart item removed successfully"
        }

    def get_cart_summary(
        self,
        db: Session,
        user_id: int,
    ):

        self._get_user_by_id(db, user_id)

        cart_items = (
            self.cart_repository.get_cart_items_with_products(
                db,
                user_id,
            )
        )

        total_items = len(cart_items)

        total_quantity = sum(
            cart_item.quantity
            for cart_item in cart_items
        )

        total_amount = Decimal("0.00")

        for cart_item in cart_items:

            if cart_item.product is None:
                raise HTTPException(
                    status_code=status.HTTP_404_NOT_FOUND,
                    detail="Product associated with cart item was not found",
                )

            product_price = Decimal(
                str(cart_item.product.price)
            )

            total_amount += (
                product_price * cart_item.quantity
            )

        return CartSummaryResponse(
            items=cart_items,
            total_items=total_items,
            total_quantity=total_quantity,
            total_amount=total_amount,
        )

    def clear_cart(
        self,
        db: Session,
        user_id: int,
    ):

        self._get_user_by_id(db, user_id)

        self.cart_repository.delete_cart_items_by_user(
            db,
            user_id,
        )

        return {
            "message": "Cart cleared successfully"
        }
