# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: app/routers/product_router.py
from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session

from app.database import get_db
from schemas.product_schema import (
    ProductCreate,
    ProductResponse,
    ProductUpdate,
)
from services.product_service import ProductService


router = APIRouter(
    prefix="/products",
    tags=["Products"],
)


product_service = ProductService()


@router.post("/",response_model=ProductResponse)
def create_product(product: ProductCreate,db: Session = Depends(get_db)):
    return product_service.create_product(db,product)


@router.get("/",response_model=list[ProductResponse])
def get_all_products(db: Session = Depends(get_db)):
    return product_service.get_all_products(db)


# Keep this route before /{product_id}
@router.get("/search",response_model=list[ProductResponse])
def search_products(
    name: str | None = None,
    category_id: int | None = None,
    db: Session = Depends(get_db),
):
    return product_service.search_products(
        db,
        name,
        category_id,
    )


@router.get(
    "/{product_id}",
    response_model=ProductResponse,
)
def get_product_by_id(
    product_id: int,
    db: Session = Depends(get_db),
):
    return product_service.get_product_by_id(
        db,
        product_id,
    )


@router.put(
    "/{product_id}",
    response_model=ProductResponse,
)
def update_product(
    product_id: int,
    product_data: ProductUpdate,
    db: Session = Depends(get_db),
):
    return product_service.update_product(
        db,
        product_id,
        product_data,
    )


@router.delete(
    "/{product_id}",
)
def delete_product(
    product_id: int,
    db: Session = Depends(get_db),
):
    return product_service.delete_product(
        db,
        product_id,
    )
