# filename: test/routes/test_product_router.py | Code Generated by Sidekick is for learning and experimentation purposes only.
from decimal import Decimal
from uuid import uuid4

from app.models.category import Category
from app.models.product import Product
from app.models.user import User


PRODUCTS_URL = "/products/"
SEARCH_URL = "/products/search"
REGISTER_URL = "/users/register"
LOGIN_URL = "/auth/login"


def create_user_payload() -> dict:
    return {
        "name": "Product Test User",
        "email": f"user_{uuid4().hex[:8]}@example.com",
        "password": "Password123",
        "mobile": "9876543210",
    }


def register_user(client) -> tuple[dict, dict]:
    payload = create_user_payload()

    response = client.post(
        REGISTER_URL,
        json=payload,
    )

    assert response.status_code in (200, 201)

    return payload, response.json()


def login_user(
    client,
    user_payload: dict,
) -> str:
    response = client.post(
        LOGIN_URL,
        data={
            "username": user_payload["email"],
            "password": user_payload["password"],
        },
    )

    assert response.status_code == 200

    return response.json()["access_token"]


def create_admin_headers(
    client,
    db_session,
) -> dict:
    user_payload, user_data = register_user(client)

    user = (
        db_session.query(User)
        .filter(
            User.user_id == user_data["user_id"],
        )
        .first()
    )

    assert user is not None

    user.role = "admin"
    db_session.commit()

    token = login_user(
        client,
        user_payload,
    )

    return {
        "Authorization": f"Bearer {token}",
    }


def create_customer_headers(client) -> dict:
    user_payload, _ = register_user(client)

    token = login_user(
        client,
        user_payload,
    )

    return {
        "Authorization": f"Bearer {token}",
    }


def seed_category(db_session) -> Category:
    category = Category(
        category_name=f"Category {uuid4().hex[:8]}",
    )

    db_session.add(category)
    db_session.commit()
    db_session.refresh(category)

    return category


def seed_product(
    db_session,
    category: Category,
) -> Product:
    product = Product(
        product_name=f"Product {uuid4().hex[:8]}",
        description="Test product",
        category=category,
        price=Decimal("25.50"),
        available_quantity=10,
        product_url="https://example.com/product",
    )

    db_session.add(product)
    db_session.commit()
    db_session.refresh(product)

    return product


def product_payload(category_id: int) -> dict:
    return {
        "product_name": f"New Product {uuid4().hex[:8]}",
        "description": "Product created through the API",
        "category_id": category_id,
        "price": "50.00",
        "available_quantity": 20,
        "product_url": "https://example.com/new-product",
    }


def test_get_all_products(client, db_session):
    category = seed_category(db_session)
    product = seed_product(
        db_session,
        category,
    )

    response = client.get(PRODUCTS_URL)

    assert response.status_code == 200

    products = response.json()

    assert len(products) == 1
    assert products[0]["product_id"] == product.product_id
    assert products[0]["product_name"] == product.product_name


def test_get_product_by_id(client, db_session):
    category = seed_category(db_session)
    product = seed_product(
        db_session,
        category,
    )

    response = client.get(
        f"{PRODUCTS_URL}{product.product_id}",
    )

    assert response.status_code == 200

    response_data = response.json()

    assert response_data["product_id"] == product.product_id
    assert response_data["product_name"] == product.product_name
    assert Decimal(str(response_data["price"])) == Decimal(
        "25.50",
    )


def test_search_products_by_name(
    client,
    db_session,
):
    category = seed_category(db_session)
    product = seed_product(
        db_session,
        category,
    )

    response = client.get(
        SEARCH_URL,
        params={
            "name": product.product_name,
        },
    )

    assert response.status_code == 200

    products = response.json()

    assert len(products) == 1
    assert products[0]["product_id"] == product.product_id


def test_search_products_by_category(
    client,
    db_session,
):
    category = seed_category(db_session)
    product = seed_product(
        db_session,
        category,
    )

    response = client.get(
        SEARCH_URL,
        params={
            "category_id": category.category_id,
        },
    )

    assert response.status_code == 200

    products = response.json()

    assert len(products) == 1
    assert products[0]["product_id"] == product.product_id


def test_get_product_not_found(client):
    response = client.get(
        f"{PRODUCTS_URL}999999",
    )

    assert response.status_code == 404
    assert response.json()["detail"] == "Product not found"


def test_create_product_as_admin(
    client,
    db_session,
):
    headers = create_admin_headers(
        client,
        db_session,
    )

    category = seed_category(db_session)

    response = client.post(
        PRODUCTS_URL,
        json=product_payload(category.category_id),
        headers=headers,
    )

    assert response.status_code == 200

    response_data = response.json()

    assert response_data["product_id"] > 0
    assert response_data["category_id"] == category.category_id
    assert response_data["available_quantity"] == 20
    assert Decimal(str(response_data["price"])) == Decimal(
        "50.00",
    )


def test_create_product_requires_admin(
    client,
    db_session,
):
    headers = create_customer_headers(client)
    category = seed_category(db_session)

    response = client.post(
        PRODUCTS_URL,
        json=product_payload(category.category_id),
        headers=headers,
    )

    assert response.status_code == 403


def test_create_product_without_token(
    client,
    db_session,
):
    category = seed_category(db_session)

    response = client.post(
        PRODUCTS_URL,
        json=product_payload(category.category_id),
    )

    assert response.status_code == 401


def test_create_product_with_missing_category(
    client,
    db_session,
):
    headers = create_admin_headers(
        client,
        db_session,
    )

    response = client.post(
        PRODUCTS_URL,
        json=product_payload(999999),
        headers=headers,
    )

    assert response.status_code == 404
    assert response.json()["detail"] == "Category not found"


def test_duplicate_product_name_is_rejected(
    client,
    db_session,
):
    headers = create_admin_headers(
        client,
        db_session,
    )

    category = seed_category(db_session)
    payload = product_payload(category.category_id)

    first_response = client.post(
        PRODUCTS_URL,
        json=payload,
        headers=headers,
    )

    assert first_response.status_code == 200

    second_response = client.post(
        PRODUCTS_URL,
        json=payload,
        headers=headers,
    )

    assert second_response.status_code == 400
    assert second_response.json()["detail"] == (
        "Product name already exists"
    )


def test_update_product_as_admin(
    client,
    db_session,
):
    headers = create_admin_headers(
        client,
        db_session,
    )

    category = seed_category(db_session)
    product = seed_product(
        db_session,
        category,
    )

    response = client.put(
        f"{PRODUCTS_URL}{product.product_id}",
        json={
            "price": "30.00",
            "available_quantity": 15,
        },
        headers=headers,
    )

    assert response.status_code == 200

    response_data = response.json()

    assert response_data["product_id"] == product.product_id
    assert Decimal(str(response_data["price"])) == Decimal(
        "30.00",
    )
    assert response_data["available_quantity"] == 15


def test_delete_product_as_admin(
    client,
    db_session,
):
    headers = create_admin_headers(
        client,
        db_session,
    )

    category = seed_category(db_session)
    product = seed_product(
        db_session,
        category,
    )

    response = client.delete(
        f"{PRODUCTS_URL}{product.product_id}",
        headers=headers,
    )

    assert response.status_code == 200
    assert response.json()["message"] == (
        "Product deleted successfully"
    )

    get_response = client.get(
        f"{PRODUCTS_URL}{product.product_id}",
    )

    assert get_response.status_code == 404
